name: Schedule Build AriaNg image

on:
  # 每周一自动构建
  schedule:
    - cron: 0 0 * * 1
  push:
    branches:
      master
    paths:
      - ".github/workflows/schedule_build.yml"
      - ".Dockerfile"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get latest release version
      run: |
        version=$(curl -s https://api.github.com/repos/mayswind/AriaNg/releases/latest | grep tag_name |cut -d '"' -f4)
        echo "::set-env name=version::$version"

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crazygit/aria_ng
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        buildargs: version
        tags: "latest,${{ env.version }}"
