name: Schedule Build AriaNg image

on:
  # 每周一自动构建
  schedule:
    - cron: 0 0 * * 1
  push:
    branches:
      master
    paths:
      - ".github/workflows/schedule_build.yml"
      - ".Dockerfile"


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get latest release version
      run: |
        version=$(curl -s https://api.github.com/repos/mayswind/AriaNg/releases/latest | grep tag_name |cut -d '"' -f4)
        echo "version=$version" >> $GITHUB_ENV

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crazygit/aria_ng
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        buildargs: version
        tags: "latest,${{ env.version }}"

    - name: Touch change every first day of month
      run: if ! $(grep -q "$(date +'%F')" .keep_alive); then echo $(date +'%F') >> .keep_alive; fi

    - name: Auto Commit to keep Scheduled workflows alive
      uses: EndBug/add-and-commit@v7
      with:
        author_name: crazygit
        author_email: lianglin999@gmail.com
        message: 'Auto Commit to keep Scheduled workflows alive'
        add: .keep_alive
